<?php
// Customers for Disconnection Report
// Criteria: 60+ days overdue OR status = 'hold_disconnection' with 45+ days overdue

$sql = "SELECT 
        c.customer_id,
        c.account_number,
        c.subscriber_name,
        c.address,
        c.tel_no,
        a.area_name,
        c.status,
        c.monthly_fee,
        COUNT(DISTINCT b.billing_id) as unpaid_bills_count,
        MIN(b.due_date) as oldest_due_date,
        MAX(p.payment_date) as last_payment_date,
        SUM(b.net_amount - COALESCE((SELECT SUM(amount_paid) FROM payments WHERE billing_id = b.billing_id), 0)) as total_balance
        FROM customers c
        LEFT JOIN areas a ON c.area_id = a.area_id
        JOIN billings b ON c.customer_id = b.customer_id
        LEFT JOIN payments p ON c.customer_id = p.customer_id
        WHERE b.status IN ('unpaid', 'partial')
        AND c.status != 'disconnected'";

if ($area_filter > 0) {
    $sql .= " AND c.area_id = $area_filter";
}

$sql .= " GROUP BY c.customer_id, c.account_number, c.subscriber_name, c.address, c.tel_no, a.area_name, c.status, c.monthly_fee
          HAVING total_balance > 0
          ORDER BY oldest_due_date ASC";

$all_customers = $conn->query($sql);

// Filter for disconnection candidates
$disconnection_candidates = [];
$total_to_disconnect = 0;
$total_balance_loss = 0;

while ($row = $all_customers->fetch_assoc()) {
    $days_overdue = $row['oldest_due_date'] ? 
        floor((strtotime('now') - strtotime($row['oldest_due_date'])) / (60 * 60 * 24)) : 0;
    
    // Criteria for disconnection
    $should_disconnect = false;
    $reason = '';
    
    if ($days_overdue >= 60 && $row['status'] == 'active') {
        $should_disconnect = true;
        $reason = '60+ days overdue';
    } elseif ($days_overdue >= 45 && $row['status'] == 'hold_disconnection') {
        $should_disconnect = true;
        $reason = 'Hold period expired (45+ days)';
    }
    
    if ($should_disconnect) {
        $row['days_overdue'] = $days_overdue;
        $row['disconnection_reason'] = $reason;
        $disconnection_candidates[] = $row;
        $total_to_disconnect++;
        $total_balance_loss += $row['total_balance'];
    }
}
?>

<div class="report-header">
    <h1>AR NOVALINK DIGITAL SYSTEMS CORP.</h1>
    <p>Customers Recommended for Disconnection</p>
    <p>As of <?php echo date('F d, Y'); ?></p>
</div>

<div class="report-info">
    <div>
        <strong>Report Generated:</strong> <?php echo date('F d, Y h:i A'); ?>
    </div>
    <div>
        <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['full_name']); ?>
    </div>
    <div>
        <strong>Filter:</strong> 
        <?php 
        if ($area_filter > 0) {
            $areas->data_seek(0);
            while ($area = $areas->fetch_assoc()) {
                if ($area['area_id'] == $area_filter) {
                    echo htmlspecialchars($area['area_name']);
                    break;
                }
            }
        } else {
            echo "All Areas";
        }
        ?>
    </div>
    <div>
        <strong>Criteria:</strong> 60+ days overdue OR Hold period expired
    </div>
</div>

<div style="margin-bottom: 20px; padding: 15px; background: #f8d7da; border-left: 4px solid #dc3545; border-radius: 5px;">
    <h3 style="color: #721c24; margin-bottom: 10px;">🚫 URGENT: Disconnection Action Required</h3>
    <p style="margin: 0;">
        The following <strong><?php echo $total_to_disconnect; ?> customer(s)</strong> meet the criteria for service disconnection.
        Total outstanding balance: <strong><?php echo format_currency($total_balance_loss); ?></strong>
    </p>
</div>

<table>
    <thead>
        <tr style="background: #dc3545; color: white;">
            <th>Account #</th>
            <th>Customer Name</th>
            <th>Address</th>
            <th>Area</th>
            <th>Contact</th>
            <th>Monthly Fee</th>
            <th>Unpaid Bills</th>
            <th>Days Overdue</th>
            <th>Last Payment</th>
            <th>Total Balance</th>
            <th>Reason</th>
        </tr>
    </thead>
    <tbody>
        <?php if (count($disconnection_candidates) > 0): ?>
            <?php foreach ($disconnection_candidates as $row): ?>
            <tr style="background: <?php echo $row['days_overdue'] > 90 ? '#f8d7da' : '#fff3cd'; ?>;">
                <td><strong><?php echo htmlspecialchars($row['account_number']); ?></strong></td>
                <td><?php echo htmlspecialchars($row['subscriber_name']); ?></td>
                <td><?php echo htmlspecialchars($row['address']); ?></td>
                <td><?php echo htmlspecialchars($row['area_name'] ?? 'N/A'); ?></td>
                <td><?php echo htmlspecialchars($row['tel_no'] ?? 'N/A'); ?></td>
                <td><?php echo format_currency($row['monthly_fee']); ?></td>
                <td class="text-center">
                    <span class="badge badge-danger"><?php echo $row['unpaid_bills_count']; ?> months</span>
                </td>
                <td class="text-center">
                    <span class="badge badge-danger"><?php echo $row['days_overdue']; ?> days</span>
                </td>
                <td><?php echo $row['last_payment_date'] ? date('M d, Y', strtotime($row['last_payment_date'])) : 'No payments'; ?></td>
                <td class="text-right"><strong style="color: #dc3545;"><?php echo format_currency($row['total_balance']); ?></strong></td>
                <td><?php echo htmlspecialchars($row['disconnection_reason']); ?></td>
            </tr>
            <?php endforeach; ?>
            <tr style="background: var(--danger-color); color: white; font-weight: bold; font-size: 15px;">
                <td colspan="9" class="text-right">TOTAL BALANCE AT RISK:</td>
                <td class="text-right"><?php echo format_currency($total_balance_loss); ?></td>
                <td></td>
            </tr>
        <?php else: ?>
            <tr>
                <td colspan="11" class="text-center" style="padding: 30px;">
                    <span style="color: var(--success-color); font-size: 18px;">
                        ✓ No customers currently meet disconnection criteria
                    </span>
                </td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<?php if (count($disconnection_candidates) > 0): ?>
<div style="margin-top: 30px; padding: 15px; background: var(--light-gray); border-radius: 5px;">
    <h3 style="color: var(--primary-color); margin-bottom: 10px;">Disconnection Summary</h3>
    <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px;">
        <div>
            <strong>Total for Disconnection:</strong> <?php echo number_format($total_to_disconnect); ?> customers
        </div>
        <div>
            <strong>Total Balance at Risk:</strong> <?php echo format_currency($total_balance_loss); ?>
        </div>
        <div>
            <strong>Average Balance:</strong> 
            <?php echo format_currency($total_to_disconnect > 0 ? $total_balance_loss / $total_to_disconnect : 0); ?>
        </div>
        <div>
            <strong>Potential Monthly Loss:</strong>
            <?php 
            $monthly_loss = 0;
            foreach ($disconnection_candidates as $cust) {
                $monthly_loss += $cust['monthly_fee'];
            }
            echo format_currency($monthly_loss);
            ?>
        </div>
    </div>
</div>

<div style="margin-top: 20px; padding: 15px; background: #d1ecf1; border-left: 4px solid #17a2b8; border-radius: 5px;">
    <h4 style="margin-bottom: 10px;">📋 Recommended Actions:</h4>
    <ol style="margin-left: 20px; line-height: 2;">
        <li><strong>Send Final Notice:</strong> Issue disconnection warning via SMS/Letter</li>
        <li><strong>Grace Period:</strong> Allow 5-7 days for payment</li>
        <li><strong>Document Attempts:</strong> Log all communication with customer</li>
        <li><strong>Disconnect Service:</strong> If no response after grace period</li>
        <li><strong>Update System:</strong> Change status to "Disconnected" in system</li>
        <li><strong>Equipment Recovery:</strong> Schedule router/equipment retrieval</li>
    </ol>
</div>

<div style="margin-top: 20px; padding: 15px; background: #fff3cd; border-left: 4px solid #ffc107; border-radius: 5px;">
    <h4 style="margin-bottom: 10px;">⚠️ Disconnection Criteria:</h4>
    <ul style="margin-left: 20px; line-height: 2;">
        <li><strong>Active Status:</strong> 60 or more days overdue</li>
        <li><strong>Hold Disconnection Status:</strong> 45 or more days overdue (grace period expired)</li>
    </ul>
</div>
<?php endif; ?>

<div style="margin-top: 40px; padding: 20px; border-top: 2px solid var(--danger-color);">
    <p style="text-align: center; color: var(--dark-gray); font-size: 12px;">
        <strong>CONFIDENTIAL REPORT:</strong> This document contains sensitive customer information and recommended disconnection actions.
        Handle in accordance with company policies and customer privacy guidelines.
    </p>
</div>