<?php
// Last Payment Dates Report
$sql = "SELECT 
        c.customer_id,
        c.account_number,
        c.subscriber_name,
        c.address,
        c.tel_no,
        a.area_name,
        c.status,
        c.monthly_fee,
        c.date_connected,
        MAX(p.payment_date) as last_payment_date,
        MAX(p.or_number) as last_or_number,
        MAX(p.amount_paid) as last_amount_paid,
        COUNT(DISTINCT p.payment_id) as total_payments,
        SUM(p.amount_paid) as lifetime_total_paid,
        (SELECT SUM(b.net_amount - COALESCE((SELECT SUM(amount_paid) FROM payments WHERE billing_id = b.billing_id), 0))
         FROM billings b 
         WHERE b.customer_id = c.customer_id 
         AND b.status IN ('unpaid', 'partial')) as current_balance
        FROM customers c
        LEFT JOIN areas a ON c.area_id = a.area_id
        LEFT JOIN payments p ON c.customer_id = p.customer_id
        WHERE c.status IN ('active', 'hold_disconnection')";

if ($area_filter > 0) {
    $sql .= " AND c.area_id = $area_filter";
}

$sql .= " GROUP BY c.customer_id, c.account_number, c.subscriber_name, c.address, c.tel_no, 
                   a.area_name, c.status, c.monthly_fee, c.date_connected
          ORDER BY last_payment_date IS NULL, last_payment_date DESC, c.subscriber_name";

$customers = $conn->query($sql);
?>

<div class="report-header">
    <h1>AR NOVALINK DIGITAL SYSTEMS CORP.</h1>
    <p>Last Payment Dates Report</p>
    <p>As of <?php echo date('F d, Y'); ?></p>
</div>

<div class="report-info">
    <div>
        <strong>Report Generated:</strong> <?php echo date('F d, Y h:i A'); ?>
    </div>
    <div>
        <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['full_name']); ?>
    </div>
    <div>
        <strong>Filter:</strong> 
        <?php 
        if ($area_filter > 0) {
            $areas->data_seek(0);
            while ($area = $areas->fetch_assoc()) {
                if ($area['area_id'] == $area_filter) {
                    echo htmlspecialchars($area['area_name']);
                    break;
                }
            }
        } else {
            echo "All Areas";
        }
        ?>
    </div>
    <div>
        <strong>Status Filter:</strong> Active & Hold Disconnection
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Account #</th>
            <th>Customer Name</th>
            <th>Area</th>
            <th>Contact</th>
            <th>Monthly Fee</th>
            <th>Last Payment Date</th>
            <th>Last OR #</th>
            <th>Last Amount</th>
            <th>Days Since Payment</th>
            <th>Total Payments</th>
            <th>Lifetime Paid</th>
            <th>Current Balance</th>
            <th>Payment Status</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($customers->num_rows > 0): ?>
            <?php 
            $total_customers = 0;
            $customers_with_payments = 0;
            $customers_no_payments = 0;
            $total_lifetime = 0;
            $total_balance = 0;
            ?>
            <?php while ($row = $customers->fetch_assoc()): 
                $total_customers++;
                $total_lifetime += $row['lifetime_total_paid'] ?? 0;
                $total_balance += $row['current_balance'] ?? 0;
                
                $days_since = null;
                if ($row['last_payment_date']) {
                    $customers_with_payments++;
                    $days_since = floor((strtotime('now') - strtotime($row['last_payment_date'])) / (60 * 60 * 24));
                } else {
                    $customers_no_payments++;
                    // Calculate days since connection
                    if ($row['date_connected']) {
                        $days_since = floor((strtotime('now') - strtotime($row['date_connected'])) / (60 * 60 * 24));
                    }
                }
                
                // Color coding based on payment frequency
                $row_class = '';
                if (!$row['last_payment_date']) {
                    $row_class = 'style="background: #f8d7da;"'; // Red - never paid
                } elseif ($days_since > 60) {
                    $row_class = 'style="background: #fff3cd;"'; // Yellow - 60+ days
                } elseif ($days_since > 90) {
                    $row_class = 'style="background: #f8d7da;"'; // Red - 90+ days
                }
            ?>
            <tr <?php echo $row_class; ?>>
                <td><?php echo htmlspecialchars($row['account_number']); ?></td>
                <td><?php echo htmlspecialchars($row['subscriber_name']); ?></td>
                <td><?php echo htmlspecialchars($row['area_name'] ?? 'N/A'); ?></td>
                <td><?php echo htmlspecialchars($row['tel_no'] ?? 'N/A'); ?></td>
                <td><?php echo format_currency($row['monthly_fee']); ?></td>
                <td>
                    <?php if ($row['last_payment_date']): ?>
                        <?php echo date('M d, Y', strtotime($row['last_payment_date'])); ?>
                    <?php else: ?>
                        <span class="badge badge-danger">No payments</span>
                    <?php endif; ?>
                </td>
                <td><?php echo $row['last_or_number'] ? htmlspecialchars($row['last_or_number']) : 'N/A'; ?></td>
                <td><?php echo $row['last_amount_paid'] ? format_currency($row['last_amount_paid']) : 'N/A'; ?></td>
                <td class="text-center">
                    <?php if ($days_since !== null): ?>
                        <?php if (!$row['last_payment_date']): ?>
                            <span class="badge badge-danger"><?php echo $days_since; ?> days (never paid)</span>
                        <?php elseif ($days_since > 90): ?>
                            <span class="badge badge-danger"><?php echo $days_since; ?> days</span>
                        <?php elseif ($days_since > 60): ?>
                            <span class="badge badge-warning"><?php echo $days_since; ?> days</span>
                        <?php elseif ($days_since > 30): ?>
                            <span class="badge badge-secondary"><?php echo $days_since; ?> days</span>
                        <?php else: ?>
                            <span class="badge badge-success"><?php echo $days_since; ?> days</span>
                        <?php endif; ?>
                    <?php else: ?>
                        N/A
                    <?php endif; ?>
                </td>
                <td class="text-center"><?php echo number_format($row['total_payments'] ?? 0); ?></td>
                <td class="text-right"><?php echo format_currency($row['lifetime_total_paid'] ?? 0); ?></td>
                <td class="text-right">
                    <?php if ($row['current_balance'] > 0): ?>
                        <strong style="color: #dc3545;"><?php echo format_currency($row['current_balance']); ?></strong>
                    <?php else: ?>
                        <span style="color: var(--success-color);">₱0.00</span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if (!$row['last_payment_date']): ?>
                        <span class="badge badge-danger">Never Paid</span>
                    <?php elseif ($days_since > 90): ?>
                        <span class="badge badge-danger">Inactive</span>
                    <?php elseif ($days_since > 60): ?>
                        <span class="badge badge-warning">Irregular</span>
                    <?php elseif ($days_since <= 30): ?>
                        <span class="badge badge-success">Regular</span>
                    <?php else: ?>
                        <span class="badge badge-secondary">Moderate</span>
                    <?php endif; ?>
                </td>
            </tr>
            <?php endwhile; ?>
            <tr style="background: var(--primary-color); color: white; font-weight: bold; font-size: 15px;">
                <td colspan="10" class="text-right">TOTALS:</td>
                <td class="text-right"><?php echo format_currency($total_lifetime); ?></td>
                <td class="text-right"><?php echo format_currency($total_balance); ?></td>
                <td></td>
            </tr>
        <?php else: ?>
            <tr>
                <td colspan="13" class="text-center">No customer records found</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<?php if ($customers->num_rows > 0): ?>
<div style="margin-top: 30px; padding: 15px; background: var(--light-gray); border-radius: 5px;">
    <h3 style="color: var(--primary-color); margin-bottom: 10px;">Payment Behavior Summary</h3>
    <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px;">
        <div>
            <strong>Total Active Customers:</strong> <?php echo number_format($total_customers); ?>
        </div>
        <div>
            <strong>Customers with Payments:</strong> 
            <span style="color: var(--success-color);"><?php echo number_format($customers_with_payments); ?></span>
        </div>
        <div>
            <strong>Never Paid:</strong> 
            <span style="color: var(--danger-color);"><?php echo number_format($customers_no_payments); ?></span>
        </div>
        <div>
            <strong>Payment Rate:</strong> 
            <?php echo $total_customers > 0 ? number_format(($customers_with_payments / $total_customers) * 100, 1) . '%' : 'N/A'; ?>
        </div>
    </div>
    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-top: 15px; padding-top: 15px; border-top: 1px solid var(--border-color);">
        <div>
            <strong>Total Lifetime Collections:</strong> <?php echo format_currency($total_lifetime); ?>
        </div>
        <div>
            <strong>Total Outstanding Balance:</strong> 
            <span style="color: var(--danger-color);"><?php echo format_currency($total_balance); ?></span>
        </div>
        <div>
            <strong>Average per Customer:</strong> 
            <?php echo format_currency($total_customers > 0 ? $total_lifetime / $total_customers : 0); ?>
        </div>
    </div>
</div>

<div style="margin-top: 20px; padding: 15px; background: #d1ecf1; border-left: 4px solid #17a2b8; border-radius: 5px;">
    <h4 style="margin-bottom: 10px;">📊 Payment Status Categories:</h4>
    <ul style="margin-left: 20px; line-height: 2;">
        <li><strong style="color: var(--success-color);">Regular (Green):</strong> Paid within last 30 days</li>
        <li><strong style="color: var(--dark-gray);">Moderate (Gray):</strong> Paid 31-60 days ago</li>
        <li><strong style="color: var(--warning-color);">Irregular (Yellow):</strong> Paid 61-90 days ago - Follow-up needed</li>
        <li><strong style="color: var(--danger-color);">Inactive (Red):</strong> 90+ days or never paid - Urgent action required</li>
    </ul>
</div>

<div style="margin-top: 20px; padding: 15px; background: #fff3cd; border-left: 4px solid #ffc107; border-radius: 5px;">
    <h4 style="margin-bottom: 10px;">⚠️ Action Items:</h4>
    <ol style="margin-left: 20px; line-height: 2;">
        <li><strong>Never Paid:</strong> Contact immediately, verify service status</li>
        <li><strong>90+ Days:</strong> Send payment reminder, consider disconnection</li>
        <li><strong>60-90 Days:</strong> Follow-up call or message</li>
        <li><strong>30-60 Days:</strong> Monitor closely</li>
    </ol>
</div>
<?php endif; ?>

<div style="margin-top: 40px; padding: 20px; border-top: 2px solid var(--primary-color);">
    <p style="text-align: center; color: var(--dark-gray); font-size: 12px;">
        This report tracks payment behavior to identify customers requiring follow-up. 
        Use this data to improve collection rates and maintain healthy customer relationships.
    </p>
</div>