<?php
// Monthly Sales Report
$sql = "SELECT 
        YEAR(p.payment_date) as year,
        MONTH(p.payment_date) as month,
        COUNT(p.payment_id) as total_transactions,
        SUM(CASE WHEN p.payment_method = 'cash' THEN p.amount_paid ELSE 0 END) as cash_payments,
        SUM(CASE WHEN p.payment_method = 'check' THEN p.amount_paid ELSE 0 END) as check_payments,
        SUM(CASE WHEN p.payment_method = 'online' THEN p.amount_paid ELSE 0 END) as online_payments,
        SUM(CASE WHEN p.payment_method = 'others' THEN p.amount_paid ELSE 0 END) as other_payments,
        SUM(p.amount_paid) as total_sales,
        COUNT(DISTINCT p.customer_id) as unique_customers
        FROM payments p
        JOIN customers c ON p.customer_id = c.customer_id";

$where_conditions = [];

// Filter by specific month/year
$where_conditions[] = "YEAR(p.payment_date) = $year_filter AND MONTH(p.payment_date) = $month_filter";

// Filter by area
if ($area_filter > 0) {
    $where_conditions[] = "c.area_id = $area_filter";
}

if (!empty($where_conditions)) {
    $sql .= " WHERE " . implode(" AND ", $where_conditions);
}

$sql .= " GROUP BY YEAR(p.payment_date), MONTH(p.payment_date)
          ORDER BY year DESC, month DESC";

$sales_data = $conn->query($sql);

// Get detailed transactions for selected month
$transactions_sql = "SELECT 
        p.or_number,
        p.payment_date,
        c.account_number,
        c.subscriber_name,
        a.area_name,
        p.amount_paid,
        p.payment_method,
        u.full_name as cashier_name
        FROM payments p
        JOIN customers c ON p.customer_id = c.customer_id
        LEFT JOIN areas a ON c.area_id = a.area_id
        LEFT JOIN users u ON p.cashier_id = u.user_id
        WHERE YEAR(p.payment_date) = $year_filter 
        AND MONTH(p.payment_date) = $month_filter";

if ($area_filter > 0) {
    $transactions_sql .= " AND c.area_id = $area_filter";
}

$transactions_sql .= " ORDER BY p.payment_date DESC, p.or_number";

$transactions = $conn->query($transactions_sql);

$grand_total = 0;
?>

<div class="report-header">
    <h1>AR NOVALINK DIGITAL SYSTEMS CORP.</h1>
    <p>Monthly Sales Report</p>
    <p><?php echo get_month_name($month_filter) . ' ' . $year_filter; ?></p>
</div>

<div class="report-info">
    <div>
        <strong>Report Generated:</strong> <?php echo date('F d, Y h:i A'); ?>
    </div>
    <div>
        <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['full_name']); ?>
    </div>
    <div>
        <strong>Report Period:</strong> <?php echo get_month_name($month_filter) . ' ' . $year_filter; ?>
    </div>
    <div>
        <strong>Area Filter:</strong> 
        <?php 
        if ($area_filter > 0) {
            $areas->data_seek(0);
            while ($area = $areas->fetch_assoc()) {
                if ($area['area_id'] == $area_filter) {
                    echo htmlspecialchars($area['area_name']);
                    break;
                }
            }
        } else {
            echo "All Areas";
        }
        ?>
    </div>
</div>

<?php if ($sales_data->num_rows > 0): ?>
    <?php 
    $row = $sales_data->fetch_assoc(); 
    $grand_total = $row['total_sales'];
    ?>
    
    <h3 style="color: var(--primary-color); margin: 20px 0 10px 0;">Sales Summary</h3>
    <table>
        <thead>
            <tr style="background: var(--primary-color); color: white;">
                <th colspan="2">Payment Method Breakdown</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><strong>Cash Payments</strong></td>
                <td class="text-right"><?php echo format_currency($row['cash_payments']); ?></td>
            </tr>
            <tr>
                <td><strong>Check Payments</strong></td>
                <td class="text-right"><?php echo format_currency($row['check_payments']); ?></td>
            </tr>
            <tr>
                <td><strong>Online Payments</strong></td>
                <td class="text-right"><?php echo format_currency($row['online_payments']); ?></td>
            </tr>
            <tr>
                <td><strong>Other Payment Methods</strong></td>
                <td class="text-right"><?php echo format_currency($row['other_payments']); ?></td>
            </tr>
            <tr style="background: var(--success-color); color: white; font-weight: bold; font-size: 16px;">
                <td><strong>TOTAL SALES</strong></td>
                <td class="text-right"><strong><?php echo format_currency($row['total_sales']); ?></strong></td>
            </tr>
        </tbody>
    </table>
    
    <div style="margin: 20px 0; padding: 15px; background: var(--light-gray); border-radius: 5px;">
        <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px;">
            <div>
                <strong>Total Transactions:</strong> <?php echo number_format($row['total_transactions']); ?>
            </div>
            <div>
                <strong>Unique Customers:</strong> <?php echo number_format($row['unique_customers']); ?>
            </div>
            <div>
                <strong>Average per Transaction:</strong> 
                <?php echo format_currency($row['total_transactions'] > 0 ? $row['total_sales'] / $row['total_transactions'] : 0); ?>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="alert alert-warning">
        <strong>No sales data found for the selected period.</strong>
    </div>
<?php endif; ?>

<h3 style="color: var(--primary-color); margin: 30px 0 10px 0;">Transaction Details</h3>
<table>
    <thead>
        <tr>
            <th>OR Number</th>
            <th>Date</th>
            <th>Account #</th>
            <th>Customer Name</th>
            <th>Area</th>
            <th>Amount</th>
            <th>Method</th>
            <th>Cashier</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($transactions->num_rows > 0): ?>
            <?php $daily_total = 0; ?>
            <?php while ($txn = $transactions->fetch_assoc()): 
                $daily_total += $txn['amount_paid'];
            ?>
            <tr>
                <td><?php echo htmlspecialchars($txn['or_number']); ?></td>
                <td><?php echo date('M d, Y', strtotime($txn['payment_date'])); ?></td>
                <td><?php echo htmlspecialchars($txn['account_number']); ?></td>
                <td><?php echo htmlspecialchars($txn['subscriber_name']); ?></td>
                <td><?php echo htmlspecialchars($txn['area_name'] ?? 'N/A'); ?></td>
                <td class="text-right"><?php echo format_currency($txn['amount_paid']); ?></td>
                <td><?php echo ucfirst($txn['payment_method']); ?></td>
                <td><?php echo htmlspecialchars($txn['cashier_name'] ?? 'N/A'); ?></td>
            </tr>
            <?php endwhile; ?>
            <tr style="background: var(--light-gray); font-weight: bold;">
                <td colspan="5" class="text-right">TOTAL:</td>
                <td class="text-right"><?php echo format_currency($daily_total); ?></td>
                <td colspan="2"></td>
            </tr>
        <?php else: ?>
            <tr>
                <td colspan="8" class="text-center">No transactions found</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<div style="margin-top: 40px; padding: 20px; border-top: 2px solid var(--primary-color);">
    <p style="text-align: center; color: var(--dark-gray); font-size: 12px;">
        This report is computer-generated and shows all payment transactions for the selected period.
    </p>
</div>