<?php
// Monthly Billing Report
$billing_date = "$year_filter-$month_filter-01";
$last_day = date('t', strtotime($billing_date));

$sql = "SELECT b.*, c.account_number, c.subscriber_name, c.address, a.area_name,
        COALESCE((SELECT SUM(amount_paid) FROM payments WHERE billing_id = b.billing_id), 0) as total_paid
        FROM billings b
        JOIN customers c ON b.customer_id = c.customer_id
        LEFT JOIN areas a ON c.area_id = a.area_id
        WHERE b.billing_month = $month_filter AND b.billing_year = $year_filter";

if ($area_filter > 0) {
    $sql .= " AND c.area_id = $area_filter";
}

$sql .= " ORDER BY a.area_name, c.subscriber_name";

$billings = $conn->query($sql);

$total_billed = 0;
$total_paid = 0;
$total_balance = 0;
?>

<div class="report-header">
    <h1>AR NOVALINK DIGITAL SYSTEMS CORP.</h1>
    <p>Monthly Billing Report</p>
    <p><?php echo get_month_name($month_filter) . ' ' . $year_filter; ?></p>
</div>

<div class="report-info">
    <div>
        <strong>Report Generated:</strong> <?php echo date('F d, Y h:i A'); ?>
    </div>
    <div>
        <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['full_name']); ?>
    </div>
    <div>
        <strong>Billing Period:</strong> <?php echo get_month_name($month_filter) . ' 1-' . $last_day . ', ' . $year_filter; ?>
    </div>
    <div>
        <strong>Area Filter:</strong> 
        <?php 
        if ($area_filter > 0) {
            $areas->data_seek(0);
            while ($area = $areas->fetch_assoc()) {
                if ($area['area_id'] == $area_filter) {
                    echo htmlspecialchars($area['area_name']);
                    break;
                }
            }
        } else {
            echo "All Areas";
        }
        ?>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Account #</th>
            <th>Customer Name</th>
            <th>Area</th>
            <th>Prev Balance</th>
            <th>Current Charges</th>
            <th>Total Billed</th>
            <th>Amount Paid</th>
            <th>Balance</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($billings->num_rows > 0): ?>
            <?php while ($row = $billings->fetch_assoc()): 
                $current_charges = $row['internet_fee'] + $row['cable_fee'] + $row['service_fee'] + $row['material_fee'];
                $balance = $row['net_amount'] - $row['total_paid'];
                $total_billed += $row['net_amount'];
                $total_paid += $row['total_paid'];
                $total_balance += $balance;
            ?>
            <tr>
                <td><?php echo htmlspecialchars($row['account_number']); ?></td>
                <td><?php echo htmlspecialchars($row['subscriber_name']); ?></td>
                <td><?php echo htmlspecialchars($row['area_name'] ?? 'N/A'); ?></td>
                <td><?php echo format_currency($row['previous_balance']); ?></td>
                <td><?php echo format_currency($current_charges); ?></td>
                <td><?php echo format_currency($row['net_amount']); ?></td>
                <td><?php echo format_currency($row['total_paid']); ?></td>
                <td><?php echo format_currency($balance); ?></td>
                <td>
                    <span class="badge badge-<?php 
                        echo $row['status'] == 'paid' ? 'success' : 
                            ($row['status'] == 'partial' ? 'warning' : 'danger'); 
                    ?>">
                        <?php echo ucfirst($row['status']); ?>
                    </span>
                </td>
            </tr>
            <?php endwhile; ?>
            <tr style="background: var(--light-gray); font-weight: bold; font-size: 15px;">
                <td colspan="5" class="text-right">TOTAL:</td>
                <td><?php echo format_currency($total_billed); ?></td>
                <td><?php echo format_currency($total_paid); ?></td>
                <td><?php echo format_currency($total_balance); ?></td>
                <td></td>
            </tr>
        <?php else: ?>
            <tr>
                <td colspan="9" class="text-center">No billing records found</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<div style="margin-top: 30px; padding: 15px; background: var(--light-gray); border-radius: 5px;">
    <h3 style="color: var(--primary-color); margin-bottom: 10px;">Summary</h3>
    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px;">
        <div>
            <strong>Total Customers:</strong> <?php echo $billings->num_rows; ?>
        </div>
        <div>
            <strong>Total Billed:</strong> <?php echo format_currency($total_billed); ?>
        </div>
        <div>
            <strong>Collection Rate:</strong> 
            <?php echo $total_billed > 0 ? number_format(($total_paid / $total_billed) * 100, 2) . '%' : 'N/A'; ?>
        </div>
    </div>
</div>