<?php
// Unpaid Accounts Report
$sql = "SELECT 
        c.customer_id,
        c.account_number,
        c.subscriber_name,
        c.address,
        c.tel_no,
        a.area_name,
        c.status,
        COUNT(DISTINCT b.billing_id) as unpaid_bills_count,
        MIN(b.due_date) as oldest_due_date,
        SUM(b.net_amount - COALESCE((SELECT SUM(amount_paid) FROM payments WHERE billing_id = b.billing_id), 0)) as total_balance
        FROM customers c
        LEFT JOIN areas a ON c.area_id = a.area_id
        JOIN billings b ON c.customer_id = b.customer_id
        WHERE b.status IN ('unpaid', 'partial')";

if ($area_filter > 0) {
    $sql .= " AND c.area_id = $area_filter";
}

$sql .= " GROUP BY c.customer_id, c.account_number, c.subscriber_name, c.address, c.tel_no, a.area_name, c.status
          HAVING total_balance > 0
          ORDER BY oldest_due_date ASC, total_balance DESC";

$unpaid_customers = $conn->query($sql);

$total_unpaid = 0;
$total_customers = 0;
?>

<div class="report-header">
    <h1>AR NOVALINK DIGITAL SYSTEMS CORP.</h1>
    <p>Unpaid Accounts Report</p>
    <p>As of <?php echo date('F d, Y'); ?></p>
</div>

<div class="report-info">
    <div>
        <strong>Report Generated:</strong> <?php echo date('F d, Y h:i A'); ?>
    </div>
    <div>
        <strong>Generated By:</strong> <?php echo htmlspecialchars($_SESSION['full_name']); ?>
    </div>
    <div>
        <strong>Filter:</strong> 
        <?php 
        if ($area_filter > 0) {
            $areas->data_seek(0);
            while ($area = $areas->fetch_assoc()) {
                if ($area['area_id'] == $area_filter) {
                    echo htmlspecialchars($area['area_name']);
                    break;
                }
            }
        } else {
            echo "All Areas";
        }
        ?>
    </div>
    <div>
        <strong>Report Date:</strong> <?php echo date('F d, Y'); ?>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Account #</th>
            <th>Customer Name</th>
            <th>Address</th>
            <th>Area</th>
            <th>Contact</th>
            <th>Unpaid Bills</th>
            <th>Oldest Due Date</th>
            <th>Days Overdue</th>
            <th>Total Balance</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
        <?php if ($unpaid_customers->num_rows > 0): ?>
            <?php while ($row = $unpaid_customers->fetch_assoc()): 
                $total_customers++;
                $total_unpaid += $row['total_balance'];
                $days_overdue = $row['oldest_due_date'] ? 
                    floor((strtotime('now') - strtotime($row['oldest_due_date'])) / (60 * 60 * 24)) : 0;
                
                // Color coding based on days overdue
                $row_class = '';
                if ($days_overdue > 60) {
                    $row_class = 'style="background: #f8d7da;"'; // Red
                } elseif ($days_overdue > 30) {
                    $row_class = 'style="background: #fff3cd;"'; // Yellow
                }
            ?>
            <tr <?php echo $row_class; ?>>
                <td><?php echo htmlspecialchars($row['account_number']); ?></td>
                <td><?php echo htmlspecialchars($row['subscriber_name']); ?></td>
                <td><?php echo htmlspecialchars($row['address']); ?></td>
                <td><?php echo htmlspecialchars($row['area_name'] ?? 'N/A'); ?></td>
                <td><?php echo htmlspecialchars($row['tel_no'] ?? 'N/A'); ?></td>
                <td class="text-center"><?php echo $row['unpaid_bills_count']; ?></td>
                <td><?php echo $row['oldest_due_date'] ? date('M d, Y', strtotime($row['oldest_due_date'])) : 'N/A'; ?></td>
                <td class="text-center">
                    <?php if ($days_overdue > 60): ?>
                        <span class="badge badge-danger"><?php echo $days_overdue; ?> days</span>
                    <?php elseif ($days_overdue > 30): ?>
                        <span class="badge badge-warning"><?php echo $days_overdue; ?> days</span>
                    <?php else: ?>
                        <span class="badge badge-secondary"><?php echo $days_overdue; ?> days</span>
                    <?php endif; ?>
                </td>
                <td class="text-right"><strong><?php echo format_currency($row['total_balance']); ?></strong></td>
                <td>
                    <span class="badge badge-<?php 
                        echo $row['status'] == 'active' ? 'success' : 
                            ($row['status'] == 'hold_disconnection' ? 'warning' : 'danger'); 
                    ?>">
                        <?php echo ucfirst(str_replace('_', ' ', $row['status'])); ?>
                    </span>
                </td>
            </tr>
            <?php endwhile; ?>
            <tr style="background: var(--primary-color); color: white; font-weight: bold; font-size: 15px;">
                <td colspan="8" class="text-right">TOTAL UNPAID:</td>
                <td class="text-right"><?php echo format_currency($total_unpaid); ?></td>
                <td></td>
            </tr>
        <?php else: ?>
            <tr>
                <td colspan="10" class="text-center">No unpaid accounts found</td>
            </tr>
        <?php endif; ?>
    </tbody>
</table>

<div style="margin-top: 30px; padding: 15px; background: var(--light-gray); border-radius: 5px;">
    <h3 style="color: var(--primary-color); margin-bottom: 10px;">Summary</h3>
    <div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px;">
        <div>
            <strong>Total Customers with Unpaid Bills:</strong> <?php echo number_format($total_customers); ?>
        </div>
        <div>
            <strong>Total Outstanding Balance:</strong> <?php echo format_currency($total_unpaid); ?>
        </div>
        <div>
            <strong>Average per Customer:</strong> 
            <?php echo format_currency($total_customers > 0 ? $total_unpaid / $total_customers : 0); ?>
        </div>
    </div>
</div>

<div style="margin-top: 20px; padding: 15px; background: #fff3cd; border-left: 4px solid #ffc107; border-radius: 5px;">
    <h4 style="margin-bottom: 10px;">⚠️ Color Coding Legend:</h4>
    <ul style="margin-left: 20px; line-height: 2;">
        <li><strong>Red Background:</strong> 60+ days overdue - URGENT ACTION REQUIRED</li>
        <li><strong>Yellow Background:</strong> 30-60 days overdue - Follow-up needed</li>
        <li><strong>White Background:</strong> Less than 30 days overdue - Monitor</li>
    </ul>
</div>

<div style="margin-top: 40px; padding: 20px; border-top: 2px solid var(--primary-color);">
    <p style="text-align: center; color: var(--dark-gray); font-size: 12px;">
        This report shows all customers with outstanding unpaid balances. Immediate action is recommended for accounts highlighted in red.
    </p>
</div>